### ISSUE TITLE
a low-level questions

### ISSUE THREAD

**Issue by Little-btf** [alcunha/iwildcam2021ufam#1]
The "README.md" file says use multiple training stages, the script classification/multi_stage_train.py can be used to automate that:
python multi_stage_train.py --annotations_json=PATH_TO_BE_CONFIGURED/iwildcam2021_train_annotations.json --megadetector_results_json=PATH_TO_BE_CONFIGURED/iwildcam2021train_originalimage_megadetector_v4.1_results_parsed.json 

but i can not find the file "iwildcam2021train_originalimage_megadetector_v4.1_results_parsed.json",where can i get it

**Comment by alcunha** [comment]
Hi @Little-btf, you can find it here: https://drive.google.com/drive/folders/19LNFfvEVmOf1NDsT0jn4v47socpFbXek?usp=sharing

**Comment by Little-btf** [comment]
> 

thank you for your response!
and i find the download link is in the "README.md" file.
I will read the document more carefully in the future
