### ISSUE TITLE
which model is used

### ISSUE THREAD

**Issue by Shawdy26256** [alcunha/iwildcam2021ufam#3]
Can you tell which model is used?
I'm not sure I expressed my question in English accurately
There are some models  for CNN like LeNet-5,AlexNet,VGG-16 and so on,
i want to know which one of them is used.

**Comment by alcunha** [comment]
I used EfficientNet-B2. You can find more details about this model here: https://arxiv.org/abs/1905.11946

However, my code also supports efficientnet-b0, efficientnet-b3, efficientnet-b4, and mobilenetv2.

**Comment by Shawdy26256** [comment]
ok,thank you for your response
