### ISSUE TITLE
a question about training model

### ISSUE THREAD

**Issue by Shawdy26256** [alcunha/iwildcam2021ufam#4]
as i know,when we train the model,we should tell the model what animals in the picture
but both in file iwildcam2021_train_annotations.json and iwildcam2021train_originalimage_megadetector_v4.1_results_parsed.json,
i can not find where mark what animals in the picture

**Comment by alcunha** [comment]
Hi,

The file iwildcam2021_train_annotations.json has both the image list and the annotations. The dataloader set the label for each image [here](https://github.com/alcunha/iwildcam2021ufam/blob/243c3e4b91d5756d1e7fcdf8ae75344a373d3b84/classification/dataloader.py#L148). The JSON is organized as follows:

```
{
  "images" : [image],
  "categories" : [category],
  "annotations" : [annotation]
}

image{
  "id" : str,
  "width" : int,
  "height" : int,
  "file_name" : str,
  "rights_holder" : str,
  "location": int,
  "sub_location": int,
  "datetime": datetime,
  "seq_id": str,
  "seq_num_frames": int,
  "frame_num": int
}

category{
  "id" : int,
  "name" : str
}

annotation{
  "id" : str,
  "image_id" : str,
  "category_id" : int
}
```
